name: TestEnviromentVariable
on: 
    workflow_dispatch:
        inputs:
            TEST:
                required: true
                default: AARUSH
                description: Simple Testing
                type: string
            Test2:
                required: true
                default: Magic
                description: Test Magic
                type: string
            Test3:
                required: true
                default: debug
                description: Enviroment 
                type: choice
                options:
                    - debug
                    - info

env:
    TEST: Karthik
    TEST2: Sandhya

jobs:
   First:   
    runs-on: ubuntu-latest
    steps:
        - name: verify
          run: echo $TEST ${{inputs.TEST}} ${{inputs.TEST2}} ${{inputs.TEST3}}
        - name: step variable
             
          run: echo $TEST $TEST2
    
    