name: TestEnviromentVariable
on: push
env:
    TEST: Karthik
    TEST2: Sandhya

jobs:
   First:   
    runs-on: ubuntu-latest
    steps:
        - name: verify
          run: echo $TEST
        - name: step variable
             
          run: echo $TEST $TEST2
    
    