name: verify
on: workflow_dispatch
jobs:
  
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
      - name: upload the file3
        uses: actions/upload-artifact@v4
        with:
          name: sample file 
          path: file3.txt
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: download artificats
        uses: actions/download-artifact@v4
        with:
          name: sample file
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
  Third:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: download artificats
        uses: actions/download-artifact@v4
        with:
          name: sample file
      - name: Executing shell script 
        run: cat file3.txt