name: verify
on: push
jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
            

