name: verify
on: push
jobs:
  
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: list files
        run: ls -altr
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: list files
        run: ls -altr
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
  third_job:
    runs-on: ubuntu-latest
    needs: second_job
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: list files
        run: ls -altr
      - name: Executing shell script 
        run: |
         chmod +x sampleScript.sh
         ./sampleScript.sh
