name: Matrix Configration

on: workflow_dispatch

jobs:
  first_job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Test 1
        run: docker info


      