name: Advanced Matrix Configration 
on: 
    workflow_dispatch: 
jobs:
    Advanced:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, windows-2022]
                image: [hello-world, alpine]
                exclude:
                    - os: windows-2022
                      image: alpine
        runs-on: ${{matrix.os}}
        steps:
            - name: OS ${{matrix.os}}
              run: docker run ${{matrix.image}}
